const enum ErrorCode {
    AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS',
    AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
    AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
    AUTH_NOT_FOUND = 'AUTH_NOT_FOUND',
    AUTH_TOO_MANY_ATTEMPTS = 'AUTH_TOO_MANY_ATTEMPTS',
    AUTH_UNAUTHORIZED_ACCESS = 'AUTH_UNAUTHORIZED_ACCESS',
    AUTH_TOKEN_NOT_FOUND = 'AUTH_TOKEN_NOT_FOUND',

    // Access Control Errors
    ACCESS_FORBIDDEN = 'ACCESS_FORBIDDEN',
    ACCESS_UNAUTHORIZED = 'ACCESS_UNAUTHORIZED',

    // Validation and Resource Errors
    VALIDATION_ERROR = 'VALIDATION_ERROR', // Thay VALIDATION_FAILED thành VALIDATION_ERROR để đồng bộ
    RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
    RESOURCE_CONFLICT = 'RESOURCE_CONFLICT', // Thêm cho ConflictException

    // System Errors
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    VERIFICATION_ERROR = 'VERIFICATION_ERROR',
    TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS', // Thêm cho TooManyRequestsException
    BAD_GATEWAY = 'BAD_GATEWAY', // Thêm cho BadGatewayException
    SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE', // Thêm cho ServiceUnavailableException
    GATEWAY_TIMEOUT = 'GATEWAY_TIMEOUT', // Thêm cho GatewayTimeoutException
}

export { ErrorCode };
